### ISSUE TITLE
self waittill / memory access out of bounds

### ISSUE THREAD

**Issue by kungfooman** [riicchhaarrd/cidscropt#3]
```js
task()
{
    self waittill("begin counting");
    printf("self = %\n", self);
}

main()
{
    o = spawnstruct();
    o thread task();
    wait 1;
    o notify("begin counting");
    printf("notifying\n");
}
```

This script fails with:

![image](https://user-images.githubusercontent.com/5236548/64918592-b866e100-d7a0-11e9-87c3-eab24d3003f7.png)

**Comment by riicchhaarrd** [comment]
you can't call threads with assigned self yet from inside the script (self <builtin_func>() methods work and from exec_ent_thread assigns self) will be added on later aswell

fix for now is to just pass the object along with the arguments instead of self

`task(o)
{
    o waittill("begin counting");
    printf("self = %\n", o);
}

main()
{
    o = spawnstruct();
    thread task(o);
    wait 1;
    o notify("begin counting");
    printf("notifying\n");
}`

**Comment by kungfooman** [comment]
Apparently fixed by:

https://github.com/riicchhaarrd/gsc/commit/5bd954f214f70338ac6d4626b043fcccc5502fae

https://github.com/riicchhaarrd/gsc/commit/712daad57ae0a911b5673f56a5c5daa1610a45a2

Screenshot from @riicchhaarrd on Discord:

![kunggsc](https://user-images.githubusercontent.com/5236548/111865535-f0d41600-8967-11eb-89f4-aae324f7010f.png)

Thank you so much for fixing! 🥇
